### ISSUE TITLE
server端启动报了错误

### ISSUE THREAD

**Issue by chuandadexiaoyu** [teaey/spring-boot-starter-dubbo-sample#6]
Server端启动报了以下错误：

Caused by: java.lang.IllegalStateException: ModuleConfig.module == null
	at com.alibaba.dubbo.config.AbstractConfig.appendParameters(AbstractConfig.java:282) ~[dubbo-2.5.4-SNAPSHOT.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.config.AbstractConfig.appendParameters(AbstractConfig.java:217) ~[dubbo-2.5.4-SNAPSHOT.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:360) ~[dubbo-2.5.4-SNAPSHOT.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:284) ~[dubbo-2.5.4-SNAPSHOT.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:245) ~[dubbo-2.5.4-SNAPSHOT.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:144) ~[dubbo-2.5.4-SNAPSHOT.jar:2.5.4-SNAPSHOT]
	at com.alibaba.dubbo.config.spring.AnnotationBean.postProcessAfterInitialization(AnnotationBean.java:195) ~[dubbo-2.5.4-SNAPSHOT.jar:2.5.4-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	... 14 common frames omitted

**Comment by bossaia** [comment]
您好，我也遇到这个问题了，您解决这个问题了吗？

**Comment by breg-jjb** [comment]
我也是这个问题，求解答啊

**Comment by breg-jjb** [comment]
https://github.com/teaey/spring-boot-starter-dubbo/issues/300 这里解决了
